# Architecture
arch: cResNet18_BinAct_v2

# ===== Dataset ===== #
data: /mnt/disk1/datasets
set: CIFAR10
name: baseline

# ===== Learning Rate Policy ======== #
optimizer: adam
lr: 0.1
lr_policy: cosine_lr

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.0005
momentum: 0.9
batch_size: 256

# ===== Sparsity =========== #
conv_type: SubnetConv
bn_type: AffineBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
prune_rate: 0.3
scale_fan: True
freeze_weights: True

# ===== Hardware setup ===== #
workers: 4
